In [1]:
import pandas as pd
from sqlalchemy import create_engine

DATABASE_URL = "postgresql://postgres:harshith123@localhost:5432/nifty100warehouse"

engine = create_engine(DATABASE_URL)

In [3]:
import pandas as pd
from sqlalchemy import create_engine

DATABASE_URL = "postgresql://postgres:harshith123@localhost:5432/nifty100warehouse"

engine = create_engine(DATABASE_URL)

ml_scores = pd.read_sql(
    "SELECT * FROM fact_ml_scores",
    engine
)

ml_scores.head()

       symbol  overall_score health_label
0         ABB          24.48         POOR
1  ADANIENSOL          29.42         POOR
2    ADANIENT          52.48      AVERAGE
3  ADANIGREEN          28.78         POOR
4  ADANIPORTS          51.03      AVERAGE

In [4]:
pd.read_sql(
    """
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema='public'
    ORDER BY table_name
    """,
    engine
)

                    table_name
0                   auth_group
1       auth_group_permissions
2              auth_permission
3                    auth_user
4             auth_user_groups
5   auth_user_user_permissions
6                  dim_company
7             dim_health_label
8                   dim_sector
9                     dim_year
10            django_admin_log
11         django_content_type
12           django_migrations
13              django_session
14               fact_analysis
15          fact_balance_sheet
16              fact_cash_flow
17              fact_ml_scores
18            fact_profit_loss
19              fact_pros_cons

In [5]:
pd.read_sql(
    """
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema='public'
    ORDER BY table_name
    """,
    engine
)

                    table_name
0                   auth_group
1       auth_group_permissions
2              auth_permission
3                    auth_user
4             auth_user_groups
5   auth_user_user_permissions
6                  dim_company
7             dim_health_label
8                   dim_sector
9                     dim_year
10            django_admin_log
11         django_content_type
12           django_migrations
13              django_session
14               fact_analysis
15          fact_balance_sheet
16              fact_cash_flow
17              fact_ml_scores
18            fact_profit_loss
19              fact_pros_cons

In [7]:
pd.read_sql(
    """
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema='public'
    ORDER BY table_name
    """,
    engine
)

                    table_name
0                   auth_group
1       auth_group_permissions
2              auth_permission
3                    auth_user
4             auth_user_groups
5   auth_user_user_permissions
6                  dim_company
7             dim_health_label
8                   dim_sector
9                     dim_year
10            django_admin_log
11         django_content_type
12           django_migrations
13              django_session
14               fact_analysis
15              fact_anomalies
16          fact_balance_sheet
17              fact_cash_flow
18               fact_clusters
19              fact_ml_scores
20            fact_profit_loss
21              fact_pros_cons